services:
  dev-helios-idenity:
    image: helios-identity:latest
    container_name: dev-helios-identity
    ports:
      - "6412:8080"
      - "6413:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: unless-stopped
