services:
  prod-helios-idenity:
    image: helios-identity:latest
    container_name: prod-helios-identity
    ports:
      - "6414:8080"
      - "6415:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    restart: unless-stopped
